// src/components/SearchBox.vue
<template>
  <div class="search-bar">
    <h3>
      <input
        className='b--green bg-lightest-blue'
        type='search'
        placeholder='enter search term here'
      />
    </h3>
  </div>
</template>

<style scoped>
h3 {
  font-size: 1.2rem;
}

@media (min-width: 1024px) {
  .search-bar h1,
  .search-bar h3 {
    text-align: left;
  }
}
</style>

// src/components/SearchBox.tsx
const SearchBox = ({ searchChange }) => {
    return (
        <div className='pa2'>
            <input
                className='pa3 ba b--green'
                type='search'
                size='50'
                placeholder='enter search term here'
                onChange={searchChange}
            />
        </div>
    );
}

export default SearchBox;
